/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulatorRouteImport } from './routes/_app.simulator'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPostEventRouteImport } from './routes/_app.post-event'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppEventsIndexRouteImport } from './routes/_app.events.index'
import { Route as AppUsersCreateRouteImport } from './routes/_app.users.create'
import { Route as AppEventsNewRouteImport } from './routes/_app.events.new'
import { Route as AppEventsIdRouteImport } from './routes/_app.events.$id'
import { Route as AppEventsIdEditRouteImport } from './routes/_app.events.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPostEventRoute = AppPostEventRouteImport.update({
  id: '/post-event',
  path: '/post-event',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersCreateRoute = AppUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIdEditRoute = AppEventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppEventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/map': typeof AppMapRoute
  '/post-event': typeof AppPostEventRoute
  '/profile': typeof AppProfileRoute
  '/simulator': typeof AppSimulatorRoute
  '/events/$id': typeof AppEventsIdRouteWithChildren
  '/events/new': typeof AppEventsNewRoute
  '/users/create': typeof AppUsersCreateRoute
  '/events/': typeof AppEventsIndexRoute
  '/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/map': typeof AppMapRoute
  '/post-event': typeof AppPostEventRoute
  '/profile': typeof AppProfileRoute
  '/simulator': typeof AppSimulatorRoute
  '/events/$id': typeof AppEventsIdRouteWithChildren
  '/events/new': typeof AppEventsNewRoute
  '/users/create': typeof AppUsersCreateRoute
  '/events': typeof AppEventsIndexRoute
  '/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/map': typeof AppMapRoute
  '/_app/post-event': typeof AppPostEventRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/simulator': typeof AppSimulatorRoute
  '/_app/events/$id': typeof AppEventsIdRouteWithChildren
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/users/create': typeof AppUsersCreateRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/copilot'
    | '/dashboard'
    | '/map'
    | '/post-event'
    | '/profile'
    | '/simulator'
    | '/events/$id'
    | '/events/new'
    | '/users/create'
    | '/events/'
    | '/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/copilot'
    | '/dashboard'
    | '/map'
    | '/post-event'
    | '/profile'
    | '/simulator'
    | '/events/$id'
    | '/events/new'
    | '/users/create'
    | '/events'
    | '/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/copilot'
    | '/_app/dashboard'
    | '/_app/map'
    | '/_app/post-event'
    | '/_app/profile'
    | '/_app/simulator'
    | '/_app/events/$id'
    | '/_app/events/new'
    | '/_app/users/create'
    | '/_app/events/'
    | '/_app/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulator': {
      id: '/_app/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post-event': {
      id: '/_app/post-event'
      path: '/post-event'
      fullPath: '/post-event'
      preLoaderRoute: typeof AppPostEventRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/create': {
      id: '/_app/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AppUsersCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$id': {
      id: '/_app/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$id/edit': {
      id: '/_app/events/$id/edit'
      path: '/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof AppEventsIdEditRouteImport
      parentRoute: typeof AppEventsIdRoute
    }
  }
}

interface AppEventsIdRouteChildren {
  AppEventsIdEditRoute: typeof AppEventsIdEditRoute
}

const AppEventsIdRouteChildren: AppEventsIdRouteChildren = {
  AppEventsIdEditRoute: AppEventsIdEditRoute,
}

const AppEventsIdRouteWithChildren = AppEventsIdRoute._addFileChildren(
  AppEventsIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMapRoute: typeof AppMapRoute
  AppPostEventRoute: typeof AppPostEventRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppEventsIdRoute: typeof AppEventsIdRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppUsersCreateRoute: typeof AppUsersCreateRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMapRoute: AppMapRoute,
  AppPostEventRoute: AppPostEventRoute,
  AppProfileRoute: AppProfileRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppEventsIdRoute: AppEventsIdRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
  AppUsersCreateRoute: AppUsersCreateRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
